version: '3'
services:
  web:
    build: .
    container_name: php74
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: nome_tabela
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - '6033:3306'